//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YemekDemeti_4.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public int RestaurantID { get; set; }
        public string C_Comment { get; set; }
        public bool Confirm { get; set; }
        public bool Submitted { get; set; }
        public int OrderID { get; set; }
        public int Score { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
